In [1]:
pip install transformers datasets torch pandas scikit-learn accelerate optuna wandb

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in ./.local/lib/python3.13/site-packages (5.14.1)
Requirement already satisfied: datasets in ./.local/lib/python3.13/site-packages (5.0.1)
Requirement already satisfied: torch in ./.local/lib/python3.13/site-packages (2.13.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: accelerate in ./.local/lib/python3.13/site-packages (1.14.0)
Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting wandb
  Downloading wandb-0.28.1-py3-none-manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in ./.local/lib/python3.13/site-packages (from transformers) (1.26.0)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in ./.local/lib/python3.13/site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.local/lib/python3.13/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in ./.local/lib/python3.13/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in ./.local/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in ./.local/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.local/lib/python3.13/site-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in ./.local/lib/python3.13/site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in ./.local/lib/python3.13/site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/anaconda3/lib/python3.13/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: setuptools>=77.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.local/lib/python3.13/site-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in ./.local/lib/python3.13/site-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in ./.local/lib/python3.13/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in ./.local/lib/python3.13/site-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.local/lib/python3.13/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.1 in ./.local/lib/python3.13/site-packages (from torch) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.local/lib/python3.13/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.13/site-packages (from accelerate) (7.0.0)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.0-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (2.0.43)
Requirement already satisfied: platformdirs in /opt/anaconda3/lib/python3.13/site-packages (from wandb) (4.5.0)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>=5 in /opt/anaconda3/lib/python3.13/site-packages (from wandb) (5.29.3)
Requirement already satisfied: pydantic<3,>=2.6 in /opt/anaconda3/lib/python3.13/site-packages (from wandb) (2.12.4)
Collecting sentry-sdk>=2.0.0 (from wandb)
  Downloading sentry_sdk-2.66.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2.6->wandb) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2.6->wandb) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2.6->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.22.0)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.4.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: greenlet>=1 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
Downloading wandb-0.28.1-py3-none-manylinux_2_28_x86_64.whl (26.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 72.1 MB/s  0:00:00 eta 0:00:01
Downloading alembic-1.19.0-py3-none-any.whl (265 kB)
Downloading sentry_sdk-2.66.1-py3-none-any.whl (505 kB)
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Downloading mako-1.4.1-py3-none-any.whl (80 kB)
Installing collected packages: sentry-sdk, Mako, colorlog, alembic, wandb, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/6 [sentry-sdk]  WARNING: The script mako-render is installed in '/home/dja1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script alembic is installed in '/home/dja1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 4/6 [wandb]  WARNING: The scripts wandb and wb are installed in '/home/dja1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 5/6 [optuna]  WARNING: The script optuna is installed in '/home/dja1/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [optuna]
Successfully installed Mako-1.4.1 alembic-1.19.0 colorlog-6.12.0 optuna-4.9.0 sentry-sdk-2.66.1 wandb-0.28.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
MODEL_NAME = "GroNLP/hateBERT"

In [21]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_NAME = "GroNLP/hateBERT"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=6,
    ignore_mismatched_sizes=True,
    id2label={0: "Non-Toxic", 1: "Insults and Flaming", 2: "Other Offensive Texts", 
              3: "Hate and Harassment 	", 4: "Threats", 5: "Extremism"},
    label2id={"Non-Toxic": 0, "Insults and Flaming": 1, "Other Offensive Texts": 2,
              "Hate and Harassment 	": 3, "Threats": 4, "Extremism": 5}
    )

In [3]:
from pathlib import Path

main_dir = Path.cwd()

# Using GameTox

In [4]:
PATH_GAMETOX_TRAIN = "Existing_Datasets/GameTox/train.csv"
PATH_GAMETOX_VAL = "Existing_Datasets/GameTox/val.csv"

In [5]:
import pandas as pd

df = pd.read_csv( main_dir / PATH_GAMETOX_TRAIN )
df_2 = pd.read_csv( main_dir / PATH_GAMETOX_VAL )

In [6]:
df.head()

   index                        message  label
0  30702                        no rush    0.0
1  18607  whatever ... watch the replay    0.0
2  32901                        useless    1.0
3  25964                      3 gunmark    0.0
4  28643                            lol    0.0

In [7]:
df_2.tail()

      index                                            message  label
5362  52888                                      u are afk bot    1.0
5363  14736  gsor please learn alternative scouting positio...    1.0
5364  15844                               i fucking love putin    5.0
5365  20533                                    leo go and kill    0.0
5366  17465                           겁먹은 **끼들 처모여 있는 것처럼 꼴 좋네    0.0

In [8]:
df["label"] = df["label"].astype(int)
df_2["label"] = df_2["label"].astype(int)
df = df[["message", "label"]]
df_2 = df_2[["message", "label"]]

In [9]:
from datasets import Dataset
from transformers import set_seed

set_seed(42)

dataset_train = Dataset.from_pandas(df)
dataset_val = Dataset.from_pandas(df_2)

In [10]:
def tokenize(batch):

    return tokenizer(
        batch["message"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [11]:
tokenized_dataset_train = dataset_train.map(
    tokenize,
    batched=True
)

Map:   0%|          | 0/42959 [00:00<?, ? examples/s]

In [12]:
tokenized_dataset_val = dataset_val.map(
    tokenize,
    batched=True
)

Map:   0%|          | 0/5367 [00:00<?, ? examples/s]

# Optuna Storage for Hyperparameter Search

In [13]:
import optuna
from optuna.storages import RDBStorage

# Define persistent storage
storage = RDBStorage("sqlite:///optuna_trials.db")

study = optuna.create_study(
    study_name="HateBERT_optuna_study",
    direction="maximize",
    storage=storage,
    load_if_exists=True
)

[I 2026-08-08 13:35:24,497] Using an existing study with name 'HateBERT_optuna_study' instead of creating a new one.

In [25]:
from sklearn.metrics import average_precision_score, f1_score
import numpy as np

def softmax(x, axis=1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

def compute_objective(metrics):
    return metrics["eval_macro_F1"]

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=1
    )

    probabilities = softmax(
        logits, 
        axis=1
    )

    n_classes = logits.shape[1]

    ap_scores = []
    for i in range(n_classes):
        y_true = (labels == i).astype(int)
        y_score = probabilities[:, i]
        ap = average_precision_score(y_true, y_score)
        ap_scores.append(ap)

    return {
        "macro_AUPRC": np.mean(ap_scores),

        "macro_F1":
            f1_score(
                labels,
                predictions,
                average="macro"
            )
    }

In [ ]:
import wandb

wandb.login(key="")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /home/dja1/.netrc
wandb: Currently logged in as: dj125101308 (dj125101308-university-college-cork) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [16]:
from transformers import TrainingArguments

wandb.init(project="hf-optuna", name="HateBERT_optuna_study")

training_args = TrainingArguments(
    output_dir="./HateBERT-GameTox",
    logging_dir="./HateBERT-GameTox-logs",

    num_train_epochs=3,
    logging_strategy="epoch",

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True,

    report_to="wandb",
    run_name="HateBERT_optuna_study"
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [22]:
from transformers import Trainer


trainer = Trainer(
    model_init=model_init,

    args=training_args,

    train_dataset=
        tokenized_dataset_train,

    eval_dataset=
        tokenized_dataset_val,

    compute_metrics=
        compute_metrics,

    processing_class=
        tokenizer
)

[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [28]:
def optuna_hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-4, log=True),
        "per_device_train_batch_size": trial.suggest_categorical(
            "per_device_train_batch_size", [16, 32, 64]
        ),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 0.3),
    }

best_run = trainer.hyperparameter_search(
    direction="maximize",
    backend="optuna",
    hp_space=optuna_hp_space,
    n_trials=10,
    compute_objective=compute_objective,
    study_name="HateBERT_optuna_study",
    storage="sqlite:///optuna_trials.db",
    load_if_exists=True
)

[I 2026-08-08 14:18:08,106] Using an existing study with name 'HateBERT_optuna_study' instead of creating a new one.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 15:02:17,014] Trial 2 finished with value: 0.3208152442655474 and parameters: {'learning_rate': 2.384299699492811e-06, 'per_device_train_batch_size': 64, 'weight_decay': 0.26813629116741433}. Best is trial 2 with value: 0.3208152442655474.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 15:49:11,210] Trial 3 finished with value: 0.4668980152481348 and parameters: {'learning_rate': 1.7790892492095264e-05, 'per_device_train_batch_size': 16, 'weight_decay': 0.2355228684675923}. Best is trial 3 with value: 0.4668980152481348.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 16:33:54,542] Trial 4 finished with value: 0.46996397678642915 and parameters: {'learning_rate': 2.4194441257029894e-05, 'per_device_train_batch_size': 32, 'weight_decay': 0.09738375492625782}. Best is trial 4 with value: 0.46996397678642915.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 17:18:38,443] Trial 5 finished with value: 0.48395720895214467 and parameters: {'learning_rate': 2.717794860748917e-05, 'per_device_train_batch_size': 32, 'weight_decay': 0.2281571823779551}. Best is trial 5 with value: 0.48395720895214467.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 18:05:33,086] Trial 6 finished with value: 0.3963567619303748 and parameters: {'learning_rate': 8.84709782853016e-06, 'per_device_train_batch_size': 16, 'weight_decay': 0.18795031150950398}. Best is trial 5 with value: 0.48395720895214467.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-08-08 18:21:12,630] Trial 7 pruned.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-08-08 18:36:51,172] Trial 8 pruned.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-08-08 18:51:33,906] Trial 9 pruned.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-08-08 19:06:29,470] Trial 10 pruned.
[transformers] You passed `num_labels=6` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-08 19:50:36,100] Trial 11 finished with value: 0.3542574821297668 and parameters: {'learning_rate': 7.824356947225773e-06, 'per_device_train_batch_size': 64, 'weight_decay': 0.1464162997538629}. Best is trial 5 with value: 0.48395720895214467.

In [30]:
print(best_run)

BestRun(run_id='5', objective=0.48395720895214467, hyperparameters={'learning_rate': 2.717794860748917e-05, 'per_device_train_batch_size': 32, 'weight_decay': 0.2281571823779551}, run_summary=None)

In [64]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [78]:
def predict_toxicity(text):

    inputs = tokenizer(
    text,
    return_tensors="pt",
    truncation=True,
    padding=True,
    max_length=512
    )

    inputs = {
    key: value.to(device)
    for key, value in inputs.items()
    }


    with torch.no_grad():
        output = model(**inputs)


    probabilities = torch.softmax(
    output.logits,
    dim=1
    )

    pred = torch.argmax(
    probabilities,
    dim=1
    ).item()

    return probabilities, pred

In [86]:
model.to(device)
model.eval()

text = "you are bad"

probabilities, pred = predict_toxicity(text)

print(probabilities)
print(model.config.id2label[pred])

tensor([[1.6374e-02, 9.6471e-01, 1.6565e-02, 1.4334e-03, 5.4496e-04, 3.6862e-04]],
       device='cuda:0')
Insults and Flaming

In [71]:
df_test_set = pd.read_csv(main_dir.parent.parent / "WebScraper" / "text_data" / "Steam" / "Counter-Strike_2_labeled.csv")

In [87]:
df_test_set["label"].value_counts(normalize=True)

label
0    0.857685
2    0.079696
1    0.055028
3    0.003795
4    0.003795
Name: proportion, dtype: float64

In [81]:
model = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "hateBERT-GameTox" / "checkpoint-6444",
    id2label={0: "Non-Toxic", 1: "Insults and Flaming", 2: "Other Offensive Texts", 
              3: "Hate and Harassment 	", 4: "Threats", 5: "Extremism"},
    label2id={"Non-Toxic": 0, "Insults and Flaming": 1, "Other Offensive Texts": 2,
              "Hate and Harassment 	": 3, "Threats": 4, "Extremism": 5}
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 3701.44it/s]

In [83]:
model.to(device)
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)

In [84]:
label_list = []

for text in df_test_set["text"]:

    probabilities, pred = predict_toxicity(text)
    label_list.append(model.config.id2label[pred])

In [85]:
label_list = pd.Series(label_list)
label_list.value_counts()

Non-Toxic                400
Other Offensive Texts     64
Insults and Flaming       63
Name: count, dtype: int64