In [2]:
pip install transformers datasets torch pandas scikit-learn accelerate peft huggingface_hub bitsandbytes

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in ./.local/lib/python3.13/site-packages (5.15.0)
Requirement already satisfied: datasets in ./.local/lib/python3.13/site-packages (5.0.1)
Requirement already satisfied: torch in ./.local/lib/python3.13/site-packages (2.13.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: accelerate in ./.local/lib/python3.13/site-packages (1.14.0)
Requirement already satisfied: peft in ./.local/lib/python3.13/site-packages (0.20.0)
Requirement already satisfied: huggingface_hub in ./.local/lib/python3.13/site-packages (1.27.0)
Requirement already satisfied: bitsandbytes in ./.local/lib/python3.13/site-packages (0.50.1)
Requirement already satisfied: numpy>=1.17 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in ./.local/lib/python3.13/site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.local/lib/python3.13/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in ./.local/lib/python3.13/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /opt/anaconda3/lib/python3.13/site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in ./.local/lib/python3.13/site-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in ./.local/lib/python3.13/site-packages (from huggingface_hub) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in ./.local/lib/python3.13/site-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.10.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.local/lib/python3.13/site-packages (from datasets) (0.4.0)
Requirement already satisfied: requests>=2.32.2 in /opt/anaconda3/lib/python3.13/site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in ./.local/lib/python3.13/site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in ./.local/lib/python3.13/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/anaconda3/lib/python3.13/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: setuptools>=77.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./.local/lib/python3.13/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.local/lib/python3.13/site-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in ./.local/lib/python3.13/site-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in ./.local/lib/python3.13/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in ./.local/lib/python3.13/site-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.local/lib/python3.13/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.1 in ./.local/lib/python3.13/site-packages (from torch) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.local/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.local/lib/python3.13/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.13/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/anaconda3/lib/python3.13/site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    set_seed, 
    Trainer, 
    TrainingArguments, 
    pipeline, 
    EarlyStoppingCallback
)
from pathlib import Path
from datasets import Dataset
from sklearn.metrics import f1_score, classification_report
import numpy as np
import pandas as pd
import torch
import json

# Dataset Preperation

In [3]:
main_dir = Path.cwd()

In [5]:
PATH_GAMETOX_TRAIN = "Existing_Datasets/GameTox/train.csv"
PATH_GAMETOX_VAL = "Existing_Datasets/GameTox/val.csv"

PATH_GAMETOX_TEST_TEXT = "Existing_Datasets/GameTox/test_index_text.csv"
PATH_GAMETOX_TEST_LABELS = "Existing_Datasets/GameTox/test_index_label.csv"

In [6]:
df_train = pd.read_csv( main_dir / PATH_GAMETOX_TRAIN )
df_val = pd.read_csv( main_dir / PATH_GAMETOX_VAL )

In [7]:
df_train["label"] = df_train["label"].astype(int)
df_val["label"] = df_val["label"].astype(int)

df_train = df_train[["message", "label"]]
df_val = df_val[["message", "label"]]

In [8]:
df_train = df_train[df_train['label'] < 4]
df_val = df_val[df_val['label'] < 4]

In [9]:
set_seed(42)

dataset_train = Dataset.from_pandas(df_train)
dataset_val = Dataset.from_pandas(df_val)

In [10]:
df_test_text = pd.read_csv(main_dir / PATH_GAMETOX_TEST_TEXT)
df_test_labels = pd.read_csv(main_dir / PATH_GAMETOX_TEST_LABELS)

In [11]:
df_test = pd.concat([df_test_text['message'], df_test_labels['label']], axis=1)
df_test = df_test[df_test['label'] < 4]
df_test['label'] = df_test['label'].astype(int)

# Evaluation Function

In [12]:
def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=1
    )

    n_classes = logits.shape[1]

    report = classification_report(
        labels, 
        predictions, 
        output_dict=True, 
        zero_division=0,
        digits=4
    )
    
    per_label_precision = []
    per_label_recall = []
    per_label_f1 = []
    
    for i in range(n_classes):
        per_label_precision.append(report[str(i)]['precision'])
        per_label_recall.append(report[str(i)]['recall'])
        per_label_f1.append(report[str(i)]['f1-score'])

    return {
        "macro_F1":
            f1_score(
                labels,
                predictions,
                average="macro"
            ),

        "per_label_precision": per_label_precision,
        "per_label_recall": per_label_recall,
        "per_label_f1": per_label_f1
    }

# Training Arguments

In [13]:
def training_args(local_save_dir):
    return TrainingArguments(
        output_dir=local_save_dir,

        learning_rate=2e-5,

        per_device_train_batch_size=32,

        weight_decay=0.01,

        metric_for_best_model="macro_F1",
        greater_is_better=True, 

        eval_strategy="steps",

        warmup_steps=0.1,

        save_strategy="steps",

        num_train_epochs=3,

        save_total_limit=2
)

# HateBERT

In [12]:
MODEL_NAME_HATEBERT = "GroNLP/hateBERT"

In [13]:
tokenizer_hatebert = AutoTokenizer.from_pretrained(MODEL_NAME_HATEBERT)

model_hatebert = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME_HATEBERT,
    num_labels=4,
    ignore_mismatched_sizes=True
)

config.json:   0%|          | 0.00/1.24k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/151 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `2`.

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: GroNLP/hateBERT
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [15]:
def tokenize_hatebert(batch):
    return tokenizer_hatebert(
        batch["message"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [16]:
tokenized_dataset_train = dataset_train.map(
    tokenize_hatebert,
    batched=True
)

Map:   0%|          | 0/42875 [00:00<?, ? examples/s]

In [17]:
tokenized_dataset_val = dataset_val.map(
    tokenize_hatebert,
    batched=True
)

Map:   0%|          | 0/5357 [00:00<?, ? examples/s]

In [30]:
trainer_hatebert = Trainer(
    model=model_hatebert,

    args=training_args('./HateBERT-GameTox'),

    train_dataset=tokenized_dataset_train,

    eval_dataset=tokenized_dataset_val,

    compute_metrics=compute_metrics,

    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [31]:
trainer_hatebert.train()

[transformers] Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4000, training_loss=0.17314175224304199, metrics={'train_runtime': 2853.9019, 'train_samples_per_second': 45.07, 'train_steps_per_second': 1.409, 'total_flos': 3.367618869448704e+16, 'train_loss': 0.17314175224304199, 'epoch': 2.9850746268656714})

In [32]:
print(trainer_hatebert.state.best_model_checkpoint)

./HateBERT-GameTox/checkpoint-2500

In [14]:
model_hatebert_from_checkpoint = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "HateBERT-GameTox" / "checkpoint-2500"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [15]:
classifier = pipeline("text-classification", model=model_hatebert_from_checkpoint, tokenizer=tokenizer_hatebert)

In [16]:
preds = classifier(df_test['message'].tolist())
preds = [(model_hatebert_from_checkpoint.config.label2id[pred['label']]) for pred in preds]

In [17]:
print(classification_report(df_test['label'], preds, digits=4, zero_division=True))

              precision    recall  f1-score   support

           0     0.9462    0.9612    0.9536      4351
           1     0.7698    0.7615    0.7656       742
           2     0.5027    0.4000    0.4455       235
           3     0.6087    0.3889    0.4746        36

    accuracy                         0.9051      5364
   macro avg     0.7068    0.6279    0.6598      5364
weighted avg     0.9001    0.9051    0.9021      5364

# Detoxify

In [37]:
MODEL_NAME_DETOXIFY = "unitary/toxic-bert"

In [41]:
tokenizer_detoxify = AutoTokenizer.from_pretrained(MODEL_NAME_DETOXIFY)

model_detoxify = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME_DETOXIFY,
    num_labels=4,
    ignore_mismatched_sizes=True,
    problem_type="single_label_classification"
)

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `6`.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: unitary/toxic-bert
Key               | Status   |
------------------+----------+---------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([6]) vs model:torch.Size([4])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([6, 768]) vs model:torch.Size([4, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

In [42]:
def tokenize_detoxify(batch):
    return tokenizer_detoxify(
        batch["message"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [47]:
tokenized_dataset_train = dataset_train.map(
    tokenize_detoxify,
    batched=True
)

Map:   0%|          | 0/42875 [00:00<?, ? examples/s]

In [48]:
tokenized_dataset_val = dataset_val.map(
    tokenize_detoxify,
    batched=True
)

Map:   0%|          | 0/5357 [00:00<?, ? examples/s]

In [49]:
trainer_detoxify = Trainer(
    model=model_detoxify,

    args=training_args('./Detoxify-GameTox'),

    train_dataset=tokenized_dataset_train,

    eval_dataset=tokenized_dataset_val,

    compute_metrics=compute_metrics,

    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [50]:
trainer_detoxify.train()

[transformers] Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4000, training_loss=0.27349424743652345, metrics={'train_runtime': 2852.4613, 'train_samples_per_second': 45.093, 'train_steps_per_second': 1.409, 'total_flos': 3.367618869448704e+16, 'train_loss': 0.27349424743652345, 'epoch': 2.9850746268656714})

In [51]:
print(trainer_detoxify.state.best_model_checkpoint)

./Detoxify-GameTox/checkpoint-2500

In [52]:
model_detoxify_checkpoint = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "Detoxify-GameTox" / "checkpoint-2500"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [53]:
classifier = pipeline("text-classification", model=model_detoxify_checkpoint, tokenizer=tokenizer_detoxify)

In [54]:
preds = classifier(df_test['message'].tolist())
preds = [(model_detoxify_checkpoint.config.label2id[pred['label']]) for pred in preds]

In [55]:
print(classification_report(df_test['label'], preds, digits=4, zero_division=True))

              precision    recall  f1-score   support

           0     0.9484    0.9639    0.9561      4351
           1     0.7591    0.7898    0.7741       742
           2     0.5972    0.3660    0.4538       235
           3     0.5769    0.4167    0.4839        36

    accuracy                         0.9100      5364
   macro avg     0.7204    0.6341    0.6670      5364
weighted avg     0.9044    0.9100    0.9058      5364

# BERT

In [5]:
MODEL_NAME_BERT = "google-bert/bert-base-uncased"

In [19]:
tokenizer_bert = AutoTokenizer.from_pretrained(MODEL_NAME_BERT)

model_bert = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME_BERT,
    num_labels=4,
    ignore_mismatched_sizes=True
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
def tokenize_bert(batch):
    return tokenizer_bert(
        batch["message"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [60]:
tokenized_dataset_train = dataset_train.map(
    tokenize_bert,
    batched=True
)

Map:   0%|          | 0/42875 [00:00<?, ? examples/s]

In [61]:
tokenized_dataset_val = dataset_val.map(
    tokenize_bert,
    batched=True
)

Map:   0%|          | 0/5357 [00:00<?, ? examples/s]

In [62]:
trainer_bert = Trainer(
    model=model_bert,

    args=training_args('./BERT-GameTox'),

    train_dataset=tokenized_dataset_train,

    eval_dataset=tokenized_dataset_val,

    compute_metrics=compute_metrics,

    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [63]:
trainer_bert.train()

[transformers] Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4020, training_loss=0.29007197879440155, metrics={'train_runtime': 2904.4283, 'train_samples_per_second': 44.286, 'train_steps_per_second': 1.384, 'total_flos': 3.3843267214848e+16, 'train_loss': 0.29007197879440155, 'epoch': 3.0})

In [64]:
print(trainer_bert.state.best_model_checkpoint)

./BERT-GameTox/checkpoint-3500

In [20]:
model_bert_checkpoint = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "BERT-GameTox" / "checkpoint-3500"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [21]:
classifier = pipeline("text-classification", model=model_bert_checkpoint, tokenizer=tokenizer_bert)

In [22]:
preds = classifier(df_test['message'].tolist())
preds = [(model_bert_checkpoint.config.label2id[pred['label']]) for pred in preds]

In [23]:
print(classification_report(df_test['label'], preds, digits=4, zero_division=True))

              precision    recall  f1-score   support

           0     0.9466    0.9612    0.9538      4351
           1     0.7649    0.7763    0.7706       742
           2     0.5329    0.3787    0.4428       235
           3     0.6154    0.4444    0.5161        36

    accuracy                         0.9066      5364
   macro avg     0.7150    0.6402    0.6708      5364
weighted avg     0.9011    0.9066    0.9031      5364

# RoBERTa

In [ ]:
MODEL_NAME_ROBERTA = "FacebookAI/roberta-base"

In [ ]:
tokenizer_roberta = AutoTokenizer.from_pretrained(MODEL_NAME_ROBERTA)

model_roberta = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME_ROBERTA,
    num_labels=4,
    ignore_mismatched_sizes=True
)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
def tokenize_roberta(batch):
    return tokenizer_roberta(
        batch["message"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [ ]:
tokenized_dataset_train = dataset_train.map(
    tokenize_roberta,
    batched=True
)

Map:   0%|          | 0/42875 [00:00<?, ? examples/s]

In [ ]:
tokenized_dataset_val = dataset_val.map(
    tokenize_roberta,
    batched=True
)

Map:   0%|          | 0/5357 [00:00<?, ? examples/s]

In [ ]:
trainer_roberta = Trainer(
    model=model_roberta,

    args=training_args('./RoBERTa-GameTox'),

    train_dataset=tokenized_dataset_train,

    eval_dataset=tokenized_dataset_val,

    compute_metrics=compute_metrics,

    callbacks = [EarlyStoppingCallback(early_stopping_patience=3)]
)

In [ ]:
trainer_roberta.train()

[transformers] Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4020, training_loss=0.31146160464974776, metrics={'train_runtime': 2876.903, 'train_samples_per_second': 44.71, 'train_steps_per_second': 1.397, 'total_flos': 3.3843267214848e+16, 'train_loss': 0.31146160464974776, 'epoch': 3.0})

In [ ]:
print(trainer_roberta.state.best_model_checkpoint)

./DeBERTa-GameTox/checkpoint-4000

In [ ]:
model_roberta_checkpoint = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "RoBERTa-GameTox" / "checkpoint-4000"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
classifier = pipeline("text-classification", model=model_roberta_checkpoint, tokenizer=tokenizer_roberta)

In [38]:
preds = classifier(df_test['message'].tolist())
preds = [(model_roberta_checkpoint.config.label2id[pred['label']]) for pred in preds]

In [39]:
print(classification_report(df_test['label'], preds, digits=4, zero_division=True))

              precision    recall  f1-score   support

           0     0.9470    0.9605    0.9537      4351
           1     0.7673    0.7911    0.7790       742
           2     0.5314    0.3957    0.4537       235
           3     0.7273    0.2222    0.3404        36

    accuracy                         0.9073      5364
   macro avg     0.7432    0.5924    0.6317      5364
weighted avg     0.9024    0.9073    0.9035      5364

# Baseline Classifer (TF-IDF Logistic Regression)

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

def create_tfidf_vectorizer():
    return TfidfVectorizer(
        ngram_range=(1, 3),
        max_features=100000,
        sublinear_tf=True,
        analyzer='word',
        lowercase=False,
        min_df=2,
        max_df=0.8,
        norm='l2',
        use_idf=True
    )

In [70]:
from sklearn.linear_model import LogisticRegression

def train_baseline_model(X_train, y_train, X_val=None, y_val=None):
    
    model = LogisticRegression(
        max_iter=2000,
        random_state=42,
        C=0.5,
        class_weight='balanced',
        solver='lbfgs',
        n_jobs=-1,
        verbose=1
    )
    
    model.fit(X_train, y_train)
    
    if X_val is not None:
        val_pred = model.predict(X_val)
        val_f1 = f1_score(y_val, val_pred, average='macro')
        print(f"\nValidation Performance:")
        print(f"  Macro F1: {val_f1:.4f}")
    
    return model

In [72]:
vectorizer = create_tfidf_vectorizer()

X_train_tfidf = vectorizer.fit_transform(df_train['message'])
X_val_tfidf = vectorizer.transform(df_val['message'])

In [73]:
model_basline = train_baseline_model(X_train_tfidf, df_train['label'], X_val_tfidf, df_val['label'])

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 20 concurrent workers.

Validation Performance:
  Macro F1: 0.5179

In [74]:
X_test_tfidf = vectorizer.transform(df_test['message'])

In [75]:
y_pred = model_basline.predict(X_test_tfidf)
    
print(classification_report(df_test['label'], y_pred, digits=4))

              precision    recall  f1-score   support

           0     0.9468    0.8582    0.9003      4351
           1     0.6548    0.6442    0.6495       742
           2     0.2442    0.5787    0.3434       235
           3     0.0977    0.3611    0.1538        36

    accuracy                         0.8130      5364
   macro avg     0.4859    0.6106    0.5118      5364
weighted avg     0.8699    0.8130    0.8362      5364

# Final Robustness Analysis on other games

In [6]:
model_best = AutoModelForSequenceClassification.from_pretrained(
    main_dir / "BERT-GameTox" / "checkpoint-3500"
)
tokenizer_best = AutoTokenizer.from_pretrained(MODEL_NAME_BERT)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
classifier_best = pipeline("text-classification", model=model_best, tokenizer=tokenizer_best)

In [10]:
df_test_game_one = pd.read_csv(main_dir / "text_data" / "Steam" / "Marvel_Rivals.csv")
df_test_game_one = df_test_game_one.head(500)

In [22]:
df_test_game_one.tail()

                                                  text
495  They never will, its by design and the people ...
496  hey when we will get guest characters in marve...
497  CAN YOUY PLEASE REMOVE SG AND ANY CHARACTER TH...
498    Now if you could just make the game skill based
499        Still not removed bot games from quickplay.

In [13]:
preds = classifier_best(df_test_game_one['text'].tolist(), truncation=True, max_length=512)
preds = [(model_best.config.label2id[pred['label']]) for pred in preds]

In [28]:
with open('llm_output_game_one.json', 'r') as file:
    llm_output = json.load(file)

In [29]:
llm_labels = [o['label'] for o in llm_output]

In [30]:
print(classification_report(llm_labels, preds, digits=4))

              precision    recall  f1-score   support

           0     0.7109    0.8667    0.7811       315
           1     0.2093    0.1452    0.1714        62
           2     0.4118    0.2545    0.3146       110
           3     0.4000    0.1538    0.2222        13

    accuracy                         0.6240       500
   macro avg     0.4330    0.3551    0.3723       500
weighted avg     0.5748    0.6240    0.5884       500

In [31]:
df_test_game_two = pd.read_csv(main_dir / "text_data" / "Steam" / "Dead_by_Daylight.csv")
df_test_game_two = df_test_game_two.head(500)

In [32]:
df_test_game_two.tail()

                                                  text
495  From what I observed A lot of players live in ...
496  As a new player with quite literally 4ish hour...
497  thats kinda part of the learning curve, You ha...
498  It's kind of always been a given that starting...
499                                       high iq post

In [33]:
preds = classifier_best(df_test_game_two['text'].tolist(), truncation=True, max_length=512)
preds = [(model_best.config.label2id[pred['label']]) for pred in preds]

In [34]:
with open('llm_output_game_two.json', 'r') as file:
    llm_output = json.load(file)

llm_labels = [o['label'] for o in llm_output]

In [35]:
print(classification_report(llm_labels, preds, digits=4))

              precision    recall  f1-score   support

           0     0.8412    0.8853    0.8627       401
           1     0.4211    0.1481    0.2192        54
           2     0.1552    0.2093    0.1782        43
           3     1.0000    0.5000    0.6667         2

    accuracy                         0.7460       500
   macro avg     0.6044    0.4357    0.4817       500
weighted avg     0.7375    0.7460    0.7335       500

In [36]:
df_test_game_three = pd.read_csv(main_dir / "text_data" / "Steam" / "Team_Fortress_2.csv")
df_test_game_three = df_test_game_three.head(500)

In [37]:
df_test_game_three.tail()

                                                  text
495  Every time i come back to these forums i kinda...
496  I think they're just recycling same ♥♥♥♥ over ...
497  So what you're saying is, in Team Fortress 2, ...
498  The replies and awards say the opposite! Chang...
499               Thats why they put Scout in the game

In [38]:
preds = classifier_best(df_test_game_three['text'].tolist(), truncation=True, max_length=512)
preds = [(model_best.config.label2id[pred['label']]) for pred in preds]

In [39]:
with open('llm_output_game_three.json', 'r') as file:
    llm_output = json.load(file)

llm_labels = [o['label'] for o in llm_output]

In [40]:
print(classification_report(llm_labels, preds, digits=4))

              precision    recall  f1-score   support

           0     0.7422    0.8584    0.7961       332
           1     0.5397    0.3656    0.4359        93
           2     0.2059    0.1346    0.1628        52
           3     0.3158    0.2609    0.2857        23

    accuracy                         0.6640       500
   macro avg     0.4509    0.4049    0.4201       500
weighted avg     0.6291    0.6640    0.6398       500